version: "3"

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

services:
  php-fpm:
    build:
      context: ./php-fpm
    volumes:
      - ./php-fpm/php.ini:/usr/local/etc/php/php.ini
      - ./php-fpm/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
      - ./php-fpm/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./logs/php:/var/log/php
      - "${PROJECT_PATH}:/var/www"
    expose:
      - "9000"
    container_name: "php-5.6"
    networks:
      - backend

  nginx:
    build:
      context: ./nginx
    ports:
      - ${HOST_HTTP_PORT}:80
      - ${HOST_HTTP_PORT}:8080
      - ${HOST_HTTPS_PORT}:443
    volumes:
      - "${PROJECT_PATH}:/var/www"
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./logs/nginx:/var/log/nginx
      - ./nginx/ssl/:/etc/nginx/ssl
    container_name: "nginx"
    depends_on:
      - php-fpm
    networks:
      - frontend
      - backend

  mysql:
    build:
      context: ./mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Asia/Seoul
    volumes:
      - ~/.docker/data/mysql56:/var/lib/mysql
      - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - ${HOST_MYSQL_PORT}:3306
    container_name: "mysql-5.6"
    networks:
      - backend
